# Usar la imagen base de PHP con Apache
FROM php:7.4-apache

# Copiar los archivos del sitio al contenedor
COPY index.html /var/www/html/
COPY styles.css /var/www/html/
COPY hora.php /var/www/html/

# Exponer el puerto 80
EXPOSE 80
